import type { Question, DialogueLine } from './types';

export const INTRO_DIALOGUE: DialogueLine[] = [
  { character: 'heart', expression: 'happy', text: '¡Bienvenido al desafío! Vamos a ver cuánto sabes realmente sobre la comida que comes.' },
  { character: 'brain', expression: 'smug', text: 'Y espero que aprendas algunas cosas útiles que puedes usar fuera de este juego.' },
  { character: 'stomach', expression: 'hungry', text: '¿El ganador recibe comida?' },
  { character: 'heart', expression: 'neutral', text: '...Empecemos.' },
];

export const HOST_PRESENTATION: DialogueLine[] = [
  { character: 'heart', expression: 'happy', text: '¡Hola a todos! Soy Corazón, el presentador principal del programa.' },
  { character: 'brain', expression: 'smug', text: 'Yo soy Cerebro. Me encargo de los datos, las explicaciones y la lógica.' },
  { character: 'stomach', expression: 'hungry', text: 'Y yo soy Estómago. Me encargo de... bueno, de tener hambre.' },
  { character: 'heart', expression: 'happy', text: '¡Juntos vamos a poner a prueba tus conocimientos sobre alimentación!' },
];

export const GENERAL_TUTORIAL: DialogueLine[] = [
  { character: 'heart', expression: 'happy', text: 'Antes de empezar, te explicaremos cómo funciona el juego.' },
  { character: 'brain', expression: 'neutral', text: 'Habrá 12 actividades en total: 10 preguntas y 2 minijuegos sorpresa.' },
  { character: 'brain', expression: 'smug', text: 'El orden de las actividades es aleatorio. Nunca sabrás cuándo aparecerá un minijuego.' },
  { character: 'heart', expression: 'neutral', text: 'Cada pregunta correcta suma puntos. Si fallas, pierdes puntos.' },
  { character: 'brain', expression: 'thinking', text: 'Los minijuegos dan puntos adicionales. Cada acierto en un minijuego vale 50 puntos.' },
  { character: 'heart', expression: 'happy', text: 'Durante las preguntas tienes tres comodines, pero no se pueden usar en los minijuegos.' },
  { character: 'stomach', expression: 'hungry', text: '¿Y si acierto todo? ¿Hay premio de comida?' },
  { character: 'brain', expression: 'neutral', text: 'El objetivo es conseguir la puntuación más alta posible. Sin comida, Estómago.' },
];

export const QUESTION_TUTORIAL: DialogueLine[] = [
  { character: 'heart', expression: 'happy', text: 'Vamos a explicarte cómo funcionan las preguntas.' },
  { character: 'brain', expression: 'neutral', text: 'Cada pregunta tiene cuatro respuestas posibles. Solo una es correcta.' },
  { character: 'brain', expression: 'smug', text: 'Si respondes correctamente sin usar comodines, ganas 100 puntos.' },
  { character: 'brain', expression: 'thinking', text: 'Si fallas, pierdes 50 puntos, sin importar cuántos comodines hayas usado.' },
  { character: 'heart', expression: 'neutral', text: 'Tienes tres comodines: 50/50, Pista y Hablar con Hosts.' },
  { character: 'brain', expression: 'neutral', text: 'Cada comodín reduce los puntos máximos que puedes ganar en la pregunta actual.' },
  { character: 'brain', expression: 'smug', text: 'Sin comodines: 100 puntos. Con uno: 75. Con dos: 50. Con tres: 25.' },
  { character: 'stomach', expression: 'hungry', text: 'O sea, cuanto más ayuda pidas, menos puntos ganas. ¡Como en la vida real!' },
  { character: 'heart', expression: 'happy', text: '¡Exacto! Cada comodín solo se puede usar una vez por pregunta. ¡Suerte!' },
];

export const FOODMATCH_TUTORIAL: DialogueLine[] = [
  { character: 'heart', expression: 'happy', text: '¡Es hora de un minijuego! Se llama FOODMATCH.' },
  { character: 'brain', expression: 'neutral', text: 'Verás alimentos y categorías. Tu objetivo es emparejar cada alimento con su categoría correcta.' },
  { character: 'brain', expression: 'smug', text: 'Cada acierto vale 50 puntos. Hay 8 oportunidades. Máximo: 400 puntos.' },
  { character: 'stomach', expression: 'hungry', text: '¡Comida! ¡Por fin!' },
  { character: 'heart', expression: 'happy', text: 'Pulsa START cuando estés listo.' },
];

export const GUESSFOOD_TUTORIAL: DialogueLine[] = [
  { character: 'heart', expression: 'happy', text: '¡Nuevo minijuego! Se llama ADIVINA LA COMIDA.' },
  { character: 'brain', expression: 'neutral', text: 'Verás un alimento pixelado. Tienes que adivinar qué alimento es.' },
  { character: 'brain', expression: 'smug', text: 'Elige entre las opciones que aparecen. Cada acierto vale 50 puntos. Hay 8 rondas. Máximo: 400 puntos.' },
  { character: 'stomach', expression: 'thinking', text: '¿Comida pixelada? ¿Se puede comer pixelada?' },
  { character: 'heart', expression: 'happy', text: 'Pulsa START cuando estés listo.' },
];

export const QUESTIONS: Question[] = [
  {
    id: 1,
    category: 'Ingredientes',
    difficulty: 'Media',
    question: '¿Cuál es el componente principal utilizado para hacer las patatas Pringles?',
    options: [
      'Patata deshidratada y almidones',
      'Maíz entero',
      'Arroz inflado',
      'Harina de trigo',
    ],
    correctAnswer: 0,
    hint: 'Piensa en cómo se fabrican los productos de patata procesada. No siempre empiezan con una patata entera cortada en lonchas.',
    explanation: 'Las Pringles se hacen con copos de patata deshidratada y almidones prensados en forma uniforme, no con patatas enteras cortadas.',
    dialogueCorrect: [
      { character: 'brain', expression: 'smug', text: '¡Correcto! Las Pringles no son patatas enteras cortadas. Su masa contiene patata deshidratada y almidones.' },
      { character: 'heart', expression: 'happy', text: 'Por eso la lista de ingredientes te dice más que la foto del paquete.' },
      { character: 'stomach', expression: 'hungry', text: '¿Entonces... puedo seguir comiéndolas?' },
      { character: 'brain', expression: 'neutral', text: 'No es eso lo que he dicho.' },
    ],
    dialogueIncorrect: [
      { character: 'brain', expression: 'surprised', text: 'No exactamente. Las Pringles se hacen con patata deshidratada y almidones prensados.' },
      { character: 'heart', expression: 'neutral', text: 'Es un producto procesado, no una simple loncha. ¡Revisa la lista de ingredientes!' },
      { character: 'stomach', expression: 'hungry', text: 'De cualquier forma, saben bien.' },
    ],
    hostAdvice: [
      { character: 'brain', expression: 'thinking', text: 'Fíjate en la forma del chip. Demasiado uniforme para ser un corte simple.' },
      { character: 'heart', expression: 'happy', text: 'Está más procesado de lo que parece.' },
    ],
  },
  {
    id: 2,
    category: 'Azúcar añadido',
    difficulty: 'Media',
    question: 'Un producto etiquetado "Sin azúcar añadido" puede seguir conteniendo azúcar significativo. ¿De dónde viene ese azúcar?',
    options: [
      'Debe estar edulcorado artificialmente',
      'Azúcares naturales de los ingredientes',
      'La etiqueta siempre es incorrecta',
      'El azúcar se añade durante el envasado',
    ],
    correctAnswer: 1,
    hint: 'Algunos ingredientes traen su propio azúcar sin que nadie lo añada. Piensa en fruta, leche o concentrados de zumo.',
    explanation: 'Los productos sin azúcar añadido pueden seguir siendo ricos en azúcar de fuentes naturales como fruta, leche o concentrados de zumo.',
    dialogueCorrect: [
      { character: 'brain', expression: 'smug', text: 'Exacto. Los azúcares naturales de fruta, leche o concentrados cuentan en el total.' },
      { character: 'heart', expression: 'happy', text: '"Sin azúcar añadido" no significa "sin azúcar". ¡Lee la etiqueta nutricional!' },
      { character: 'stomach', expression: 'thinking', text: '¿Entonces la fruta tiene azúcar? ¿Pero la fruta es buena?' },
      { character: 'brain', expression: 'neutral', text: 'El contexto importa, Estómago. El contexto importa.' },
    ],
    dialogueIncorrect: [
      { character: 'brain', expression: 'surprised', text: 'Los azúcares naturales de ingredientes como fruta o leche pueden hacer un producto alto en azúcar.' },
      { character: 'heart', expression: 'neutral', text: '"Sin azúcar añadido" solo significa que no se añadió más. El total puede seguir siendo alto.' },
      { character: 'stomach', expression: 'hungry', text: 'No entiendo, pero tengo hambre.' },
    ],
    hostAdvice: [
      { character: 'heart', expression: 'thinking', text: 'Piensa en lo que ya está en los ingredientes antes de que nadie añada nada.' },
      { character: 'brain', expression: 'neutral', text: 'Fruta, leche y concentrados traen su propio azúcar.' },
    ],
  },
  {
    id: 3,
    category: 'Fibra',
    difficulty: 'Fácil',
    question: '¿Cuál de estos aperitivos es la mejor fuente de fibra dietética?',
    options: [
      'Tostada de pan blanco',
      'Un puñado de almendras',
      'Un vaso de zumo de naranja',
      'Patatas fritas',
    ],
    correctAnswer: 1,
    hint: 'La fibra viene de partes de las plantas que tu cuerpo no puede descomponer. Piensa en alimentos integrales que mantienen su estructura.',
    explanation: 'Las almendras son ricas en fibra. Los alimentos de origen vegetal integral como nueces, semillas, frutas con piel y cereales integrales son excelentes fuentes.',
    dialogueCorrect: [
      { character: 'heart', expression: 'happy', text: '¡Sí! Las almendras están llenas de fibra, que ayuda a mantener todo en movimiento.' },
      { character: 'brain', expression: 'smug', text: 'La fibra apoya la digestión, regula el azúcar en sangre y ayuda a sentirse satisfecho.' },
      { character: 'stomach', expression: 'happy', text: '¡Me encantan las almendras! Me mantienen ocupado un rato.' },
    ],
    dialogueIncorrect: [
      { character: 'brain', expression: 'surprised', text: 'La respuesta son las almendras. El pan blanco y el zumo pierden la mayor parte de su fibra en el procesado.' },
      { character: 'heart', expression: 'neutral', text: 'Los alimentos integrales mantienen su fibra. Los procesados tienden a perderla.' },
      { character: 'stomach', expression: 'sad', text: 'Quería que la respuesta fueran las patatas fritas.' },
    ],
    hostAdvice: [
      { character: 'brain', expression: 'thinking', text: 'La fibra sobrevive mal al procesado. Los alimentos integrales son tu mejor opción.' },
      { character: 'heart', expression: 'happy', text: 'Nueces, semillas, cereales integrales, fruta entera: los campeones de la fibra.' },
    ],
  },
  {
    id: 4,
    category: 'Proteína',
    difficulty: 'Media',
    question: '¿Qué opción de desayuno aporta más proteína por porción?',
    options: [
      'Un tazón de cereales de maíz con leche',
      'Una porción de yogur griego',
      'Una rebanada de pan blanco tostado',
      'Un vaso de zumo de manzana',
    ],
    correctAnswer: 1,
    hint: 'La proteína es más alta en lácteos, huevos, carne, legumbres y nueces. Piensa cuál es la fuente más concentrada aquí.',
    explanation: 'El yogur griego puede tener 15-20 g de proteína por porción, mucho más que los cereales, la tostada o el zumo.',
    dialogueCorrect: [
      { character: 'brain', expression: 'smug', text: 'Correcto. El yogur griego se cuaja, concentrando la proteína a 15-20 gramos por porción.' },
      { character: 'heart', expression: 'happy', text: 'La proteína te mantiene lleno y ayuda a tus músculos. ¡Gran forma de empezar el día!' },
      { character: 'stomach', expression: 'happy', text: 'El yogur griego es delicioso. Más, por favor.' },
    ],
    dialogueIncorrect: [
      { character: 'brain', expression: 'surprised', text: 'La respuesta es el yogur griego. Tiene mucha más proteína que los cereales o la tostada.' },
      { character: 'heart', expression: 'neutral', text: 'La proteína no es solo para culturistas. Ayuda a todos a sentirse llenos y con energía.' },
      { character: 'stomach', expression: 'thinking', text: 'Pensaba que los cereales eran fuertes.' },
    ],
    hostAdvice: [
      { character: 'heart', expression: 'thinking', text: 'Piensa en lo que es más concentrado. Lácteos y huevos son potencias de proteína.' },
      { character: 'brain', expression: 'neutral', text: 'El yogur colado tiene más proteína que el yogur normal.' },
    ],
  },
  {
    id: 5,
    category: 'Bebidas azucaradas',
    difficulty: 'Fácil',
    question: '¿Qué bebida contiene típicamente más azúcar añadido por porción estándar?',
    options: [
      'Agua con gas',
      'Un refresco de cola de 350 ml',
      'Té sin azúcar',
      'Café negro',
    ],
    correctAnswer: 1,
    hint: 'El azúcar no está solo en los postres. Algunas bebidas meten un postre entero de azúcar en una sola lata.',
    explanation: 'Un refresco de cola de 350 ml puede contener unos 39 gramos de azúcar añadido, cerca del límite diario recomendado en una sola lata.',
    dialogueCorrect: [
      { character: 'brain', expression: 'smug', text: 'Correcto. Una sola lata de cola puede tener unos 39 gramos de azúcar añadido.' },
      { character: 'heart', expression: 'surprised', text: '¡Eso es casi todo el azúcar de un día en una sola bebida!' },
      { character: 'stomach', expression: 'hungry', text: 'Pero es tan refrescante...' },
      { character: 'brain', expression: 'neutral', text: 'Refrescante no es lo mismo que nutritivo.' },
    ],
    dialogueIncorrect: [
      { character: 'brain', expression: 'surprised', text: 'La respuesta es la cola. Una lata puede tener 39 gramos de azúcar añadido.' },
      { character: 'heart', expression: 'neutral', text: 'Eso está cerca del límite diario recomendado. El azúcar líquido suma rápido.' },
      { character: 'stomach', expression: 'sad', text: 'Te echaré de menos, cola.' },
    ],
    hostAdvice: [
      { character: 'brain', expression: 'thinking', text: 'Las bebidas sin azúcar añadido tienen cero. Las otras no se acercan.' },
      { character: 'heart', expression: 'neutral', text: 'Las calorías líquidas pueden pasar desapercibidas.' },
    ],
  },
  {
    id: 6,
    category: 'Ultra-procesados',
    difficulty: 'Difícil',
    question: '¿Cuál es una característica que define a los alimentos ultra-procesados?',
    options: [
      'Siempre son altos en calorías',
      'Contienen ingredientes que no encontrarías en una cocina casera',
      'Siempre están congelados',
      'Siempre son dulces',
    ],
    correctAnswer: 1,
    hint: 'No se trata de calorías ni de temperatura. Piensa en qué hay en la etiqueta de ingredientes que nunca usarías en casa.',
    explanation: 'Los ultra-procesados contienen ingredientes industriales y aditivos que no se usan típicamente en cocina casera, como emulsionantes, conservantes y sabores artificiales.',
    dialogueCorrect: [
      { character: 'brain', expression: 'smug', text: 'Exacto. Los ultra-procesados contienen aditivos industriales que no encontrarías en una cocina casera.' },
      { character: 'heart', expression: 'happy', text: 'Si no puedes pronunciar la mitad de la lista de ingredientes, probablemente sea ultra-procesado.' },
      { character: 'stomach', expression: 'thinking', text: 'No puedo pronunciar la mitad de nada.' },
    ],
    dialogueIncorrect: [
      { character: 'brain', expression: 'surprised', text: 'La clave son los ingredientes industriales: emulsionantes, conservantes, sabores artificiales.' },
      { character: 'heart', expression: 'neutral', text: 'No se trata de calorías ni sabor. Se trata de lo lejos que está el alimento de su forma original.' },
      { character: 'stomach', expression: 'hungry', text: 'Pero me gustan los que no se pueden pronunciar.' },
    ],
    hostAdvice: [
      { character: 'brain', expression: 'thinking', text: 'Piensa en la lista de ingredientes. ¿Usarías esos ingredientes en casa?' },
      { character: 'heart', expression: 'neutral', text: 'Si suena a experimento de química, probablemente sea ultra-procesado.' },
    ],
  },
  {
    id: 7,
    category: 'Etiquetas nutricionales',
    difficulty: 'Media',
    question: 'En una etiqueta de ingredientes, ¿en qué orden se enumeran los ingredientes?',
    options: [
      'Orden aleatorio',
      'Orden alfabético',
      'Por peso, el más pesado primero',
      'Por contenido de calorías',
    ],
    correctAnswer: 2,
    hint: 'El orden no es aleatorio ni alfabético. Piensa en qué le importa más al fabricante.',
    explanation: 'Los ingredientes se enumeran por peso en orden descendente. Los primeros ingredientes componen la mayor parte del producto.',
    dialogueCorrect: [
      { character: 'brain', expression: 'smug', text: 'Correcto. Los ingredientes se enumeran por peso, el más pesado primero. Los tres primeros te dicen la mayor parte de lo que comes.' },
      { character: 'heart', expression: 'happy', text: 'Si el azúcar está primero o segundo, ¡sabes que es mayoritariamente azúcar!' },
      { character: 'stomach', expression: 'surprised', text: '¿El primero es el ingrediente principal? ¡Nunca lo supe!' },
    ],
    dialogueIncorrect: [
      { character: 'brain', expression: 'surprised', text: 'Los ingredientes se enumeran por peso, el más pesado primero. Los primeros componen la mayoría.' },
      { character: 'heart', expression: 'neutral', text: 'Revisa los tres primeros ingredientes. Eso es lo que mayormente estás comiendo.' },
      { character: 'stomach', expression: 'thinking', text: 'Siempre leí la etiqueta al revés. ¿Está mal?' },
    ],
    hostAdvice: [
      { character: 'brain', expression: 'thinking', text: 'Es un ranking. El ingrediente más abundante va primero.' },
      { character: 'heart', expression: 'neutral', text: 'Si el primer ingrediente es azúcar, el producto es mayoritariamente azúcar.' },
    ],
  },
  {
    id: 8,
    category: 'Hidratación',
    difficulty: 'Fácil',
    question: '¿Qué afirmación sobre la ingesta diaria de agua es más precisa?',
    options: [
      'Todo el mundo necesita exactamente 8 vasos de agua al día',
      'Las necesidades de agua varían según el cuerpo, la actividad y el clima',
      'El café y el té no cuentan para la hidratación',
      'Solo necesitas agua cuando sientes sed',
    ],
    correctAnswer: 1,
    hint: 'No hay un número mágico universal. Piensa en qué cambia cuánta agua necesita una persona.',
    explanation: 'Las necesidades de agua varían según el individuo. El tamaño corporal, la actividad, el clima y la dieta afectan cuánta agua necesitas. El café y el té sí contribuyen a la hidratación.',
    dialogueCorrect: [
      { character: 'brain', expression: 'smug', text: 'Correcto. La hidratación es individual. Cuerpo, actividad, clima y la comida que comes importan.' },
      { character: 'heart', expression: 'happy', text: 'Escucha a tu cuerpo. La sed es una guía, pero no esperes a estar desesperado.' },
      { character: 'stomach', expression: 'happy', text: '¡Consigo agua de la sopa! La sopa cuenta, ¿no?' },
      { character: 'brain', expression: 'neutral', text: 'Sí, Estómago. La sopa cuenta.' },
    ],
    dialogueIncorrect: [
      { character: 'brain', expression: 'surprised', text: 'La respuesta es que las necesidades varían. La regla de 8 vasos es un mito, no un estándar universal.' },
      { character: 'heart', expression: 'neutral', text: 'Tus necesidades dependen de tu cuerpo, tu actividad y tu entorno. No hay una talla única.' },
      { character: 'stomach', expression: 'thinking', text: '¿Entonces puedo beber sopa en vez de agua?' },
    ],
    hostAdvice: [
      { character: 'brain', expression: 'thinking', text: 'Piensa en qué cambia las necesidades de agua. Un corredor en el desierto necesita más que alguien sentado.' },
      { character: 'heart', expression: 'neutral', text: 'No hay un número mágico para todos.' },
    ],
  },
  {
    id: 9,
    category: 'Grasas',
    difficulty: 'Media',
    question: 'Un producto dice "0% grasa". ¿Esto significa automáticamente que es la opción más saludable?',
    options: [
      'Sí, sin grasa es siempre mejor',
      'No, puede tener más azúcar o sal para compensar el sabor',
      'Sí, la grasa siempre es mala',
      'No, porque la grasa nunca importa',
    ],
    correctAnswer: 1,
    hint: 'Cuando se quita la grasa de un alimento, algo suele añadirse para mantener el sabor. Piensa en qué podría ser.',
    explanation: 'Los productos "sin grasa" a menudo añaden más azúcar o sal para compensar la pérdida de sabor. La grasa no es siempre mala; el contexto importa.',
    dialogueCorrect: [
      { character: 'brain', expression: 'smug', text: 'Correcto. Sin grasa no significa más sano. A menudo añaden azúcar o sal para compensar el sabor.' },
      { character: 'heart', expression: 'happy', text: 'Las grasas no son enemigas. Todo depende del tipo y la cantidad.' },
      { character: 'stomach', expression: 'thinking', text: '¿Entonces la grasa no es mala? ¡Me encanta!' },
    ],
    dialogueIncorrect: [
      { character: 'brain', expression: 'surprised', text: '"Sin grasa" no significa mejor. A menudo tienen más azúcar o sal para compensar.' },
      { character: 'heart', expression: 'neutral', text: 'No todas las grasas son malas. Lo que importa es el equilibrio y la variedad.' },
      { character: 'stomach', expression: 'hungry', text: 'Pensaba que sin grasa era siempre lo mejor.' },
    ],
    hostAdvice: [
      { character: 'brain', expression: 'thinking', text: 'Cuando quitan la grasa, algo la sustituye para mantener el sabor.' },
      { character: 'heart', expression: 'neutral', text: 'Revisa el azúcar total, no solo la grusa.' },
    ],
  },
  {
    id: 10,
    category: 'Marketing alimentario',
    difficulty: 'Difícil',
    question: 'Un paquete muestra imágenes de fruta fresca y campos verdes. ¿Qué te dice esto sobre el contenido real de fruta?',
    options: [
      'El producto contiene mucha fruta real',
      'Las imágenes no garantizan nada sobre el contenido real',
      'El producto es 100% natural',
      'El producto no tiene azúcar',
    ],
    correctAnswer: 1,
    hint: 'El packaging está diseñado para vender. Lo que ves en la portada no siempre refleja lo que hay dentro.',
    explanation: 'Las imágenes del packaging están diseñadas para atraer. No garantizan el contenido. Solo la lista de ingredientes te dice qué hay realmente.',
    dialogueCorrect: [
      { character: 'brain', expression: 'smug', text: 'Correcto. Las imágenes del packaging no garantizan nada. Solo la lista de ingredientes dice la verdad.' },
      { character: 'heart', expression: 'happy', text: 'No te dejes engañar por fotos bonitas. Lee la etiqueta.' },
      { character: 'stomach', expression: 'surprised', text: '¿Entonces las fotos no son reales? ¡Me siento traicionado!' },
    ],
    dialogueIncorrect: [
      { character: 'brain', expression: 'surprised', text: 'Las imágenes del packaging no garantizan contenido real de fruta. Lee los ingredientes.' },
      { character: 'heart', expression: 'neutral', text: 'El marketing está diseñado para que compres. La etiqueta te dice la verdad.' },
      { character: 'stomach', expression: 'sad', text: 'Pensaba que había fruta de verdad.' },
    ],
    hostAdvice: [
      { character: 'brain', expression: 'thinking', text: 'El packaging vende una imagen. El contenido puede ser muy diferente.' },
      { character: 'heart', expression: 'neutral', text: 'Busca "concentrado de fruta" o "aroma": no es lo mismo que fruta real.' },
    ],
  },
  {
    id: 11,
    category: 'Variedad',
    difficulty: 'Fácil',
    question: '¿Por qué es importante comer una variedad de alimentos de diferentes colores?',
    options: [
      'Para que el plato se vea bonito',
      'Porque cada color aporta diferentes nutrientes',
      'No es importante, todos los alimentos son iguales',
      'Solo importa comer verde',
    ],
    correctAnswer: 1,
    hint: 'Los colores en frutas y verduras indican diferentes compuestos naturales. Piensa en qué aporta cada uno.',
    explanation: 'Cada color en frutas y verduras refleja diferentes nutrientes y antioxidantes. Comer variedad asegura obtener un abanico amplio de nutrientes.',
    dialogueCorrect: [
      { character: 'heart', expression: 'happy', text: '¡Exacto! Cada color trae nutrientes diferentes. La variedad es clave.' },
      { character: 'brain', expression: 'smug', text: 'Rojo, verde, naranja, morado: cada color aporta antioxidantes y vitaminas distintos.' },
      { character: 'stomach', expression: 'happy', text: '¡Me gusta comer del arcoíris! Especialmente si son dulces.' },
    ],
    dialogueIncorrect: [
      { character: 'brain', expression: 'surprised', text: 'Cada color aporta nutrientes diferentes. La variedad asegura un abanico amplio.' },
      { character: 'heart', expression: 'neutral', text: 'No se trata solo de estética. Los colores reflejan nutrientes reales.' },
      { character: 'stomach', expression: 'thinking', text: 'Pensaba que era solo para que se viera bonito.' },
    ],
    hostAdvice: [
      { character: 'heart', expression: 'thinking', text: 'Piensa en qué nutrientes representa cada color.' },
      { character: 'brain', expression: 'neutral', text: 'Licopeno rojo, beta-caroteno naranja, antocianinas moradas... cada uno es diferente.' },
    ],
  },
  {
    id: 12,
    category: 'Azúcar añadido',
    difficulty: 'Difícil',
    question: 'En una etiqueta, el azúcar puede aparecer con muchos nombres diferentes. ¿Cuál de estos NO es un tipo de azúcar añadido?',
    options: [
      'Jarabe de maíz',
      'Maltodextrina',
      'Azúcar de caña',
      'Vitamina C',
    ],
    correctAnswer: 3,
    hint: 'Algunos ingredientes suenan técnicos pero son azúcar disfrazado. Uno de estos no tiene nada que ver con el azúcar.',
    explanation: 'La maltodextrina, el jarabe de maíz y el azúcar de caña son formas de azúcar añadido. La vitamina C es un nutriente, no azúcar. Aprender los nombres del azúcar ayuda a identificarlo.',
    dialogueCorrect: [
      { character: 'brain', expression: 'smug', text: 'Correcto. La vitamina C es un nutriente. Los otros tres son azúcar con diferentes nombres.' },
      { character: 'heart', expression: 'happy', text: 'El azúcar tiene muchos disfraces. Conocerlos te ayuda a leer mejor las etiquetas.' },
      { character: 'stomach', expression: 'surprised', text: '¿El azúcar se disfraza? ¡Qué tramposo!' },
    ],
    dialogueIncorrect: [
      { character: 'brain', expression: 'surprised', text: 'La vitamina C es la respuesta. Los otros tres son azúcar con nombres diferentes.' },
      { character: 'heart', expression: 'neutral', text: 'El azúcar tiene muchos nombres. Aprenderlos te da poder sobre las etiquetas.' },
      { character: 'stomach', expression: 'thinking', text: 'Maltodextrina suena a cosa de laboratorio.' },
    ],
    hostAdvice: [
      { character: 'brain', expression: 'thinking', text: 'Tres de estos son azúcar con diferente nombre. Uno no tiene nada que ver.' },
      { character: 'heart', expression: 'neutral', text: 'Piensa en cuál es un nutriente conocido, no un edulcorante.' },
    ],
  },
  {
    id: 13,
    category: 'Etiquetas nutricionales',
    difficulty: 'Media',
    question: '¿Qué significa "porción" en una etiqueta nutricional?',
    options: [
      'La cantidad que deberías comer',
      'La cantidad de producto que el fabricante usa como referencia',
      'El tamaño del paquete entero',
      'La cantidad recomendada por el médico',
    ],
    correctAnswer: 1,
    hint: 'La porción en la etiqueta no es una recomendación de salud. Es una cantidad definida por el fabricante.',
    explanation: 'La porción es la cantidad de producto que el fabricante usa como referencia para los valores nutricionales. No es una recomendación de cuánto comer. Un paquete puede tener varias porciones.',
    dialogueCorrect: [
      { character: 'brain', expression: 'smug', text: 'Correcto. La porción es la referencia del fabricante, no una recomendación de cuánto comer.' },
      { character: 'heart', expression: 'happy', text: 'Un paquete puede tener varias porciones. ¡Comprueba cuántas antes de comerlo entero!' },
      { character: 'stomach', expression: 'surprised', text: '¿Entonces lo que yo llamo "una porción" puede ser tres en la etiqueta?' },
    ],
    dialogueIncorrect: [
      { character: 'brain', expression: 'surprised', text: 'La porción es la cantidad que el fabricante usa como referencia, no lo que deberías comer.' },
      { character: 'heart', expression: 'neutral', text: 'Un paquete puede tener varias porciones. Lee cuántas hay.' },
      { character: 'stomach', expression: 'thinking', text: 'Pensaba que era lo que me tocaba.' },
    ],
    hostAdvice: [
      { character: 'brain', expression: 'thinking', text: 'No es una recomendación. Es una cantidad definida por el fabricante.' },
      { character: 'heart', expression: 'neutral', text: 'Comprueba cuántas porciones tiene el paquete.' },
    ],
  },
  {
    id: 14,
    category: 'Ultra-procesados',
    difficulty: 'Media',
    question: '¿Cuál de estos alimentos es menos procesado?',
    options: [
      'Patatas fritas de bolsa',
      'Una patata asada',
      'Puré de patata instantáneo',
      'Galletas de patata',
    ],
    correctAnswer: 1,
    hint: 'Menos procesado significa más cerca del alimento original. ¿Cuál de estos es más parecido a una patata real?',
    explanation: 'La patata asada es el alimento menos procesado. Está en su forma natural. Los otros tres han sido transformados industrialmente con aditivos y procesos.',
    dialogueCorrect: [
      { character: 'brain', expression: 'smug', text: 'Correcto. La patata asada está en su forma natural, sin apenas procesado.' },
      { character: 'heart', expression: 'happy', text: 'Cuanto menos procesado, más cerca del alimento original. ¡Simple!' },
      { character: 'stomach', expression: 'happy', text: 'Las patatas asadas están ricas. Es un ganar-ganrar.' },
    ],
    dialogueIncorrect: [
      { character: 'brain', expression: 'surprised', text: 'La patata asada es la menos procesada. Las otras han sido transformadas con aditivos.' },
      { character: 'heart', expression: 'neutral', text: 'Menos procesado significa más cerca del alimento natural.' },
      { character: 'stomach', expression: 'sad', text: 'Pero las de bolsa están más ricas.' },
    ],
    hostAdvice: [
      { character: 'brain', expression: 'thinking', text: 'Piensa en cuál se parece más a una patata recién sacada de la tierra.' },
      { character: 'heart', expression: 'neutral', text: 'Menos pasos entre la granja y tu plato.' },
    ],
  },
  {
    id: 15,
    category: 'Decisiones prácticas',
    difficulty: 'Fácil',
    question: 'Estás en un restaurante y te ofrecen ensalada o patatas fritas como guarnición. ¿Qué es lo más equilibrado?',
    options: [
      'Siempre la ensalada, sin excepción',
      'Depende del resto de tu comida del día',
      'Siempre las patatas fritas',
      'No importa, come lo que tenga mejor sabor',
    ],
    correctAnswer: 1,
    hint: 'No hay una respuesta universal. Piensa en el contexto de todo lo que has comido hoy.',
    explanation: 'La elección depende del contexto. Si tu comida del día ya tiene muchas verduras, las patatas pueden encajar. Si no, la ensalada ayuda a equilibrar. La variedad y el equilibrio importan más que reglas fijas.',
    dialogueCorrect: [
      { character: 'brain', expression: 'smug', text: 'Correcto. Depende del contexto de toda tu comida del día. No hay reglas fijas.' },
      { character: 'heart', expression: 'happy', text: 'Se trata de equilibrio y variedad, no de reglas rígidas.' },
      { character: 'stomach', expression: 'thinking', text: '¿Entonces puedo elegir patatas a veces? ¡Eso me gusta!' },
    ],
    dialogueIncorrect: [
      { character: 'brain', expression: 'surprised', text: 'Depende del contexto. Piensa en lo que ya has comido hoy.' },
      { character: 'heart', expression: 'neutral', text: 'No hay una respuesta universal. El equilibrio es lo que importa.' },
      { character: 'stomach', expression: 'happy', text: '¡Me gusta que no haya reglas estrictas!' },
    ],
    hostAdvice: [
      { character: 'brain', expression: 'thinking', text: 'Piensa en todo lo que has comido hoy, no solo en este plato.' },
      { character: 'heart', expression: 'neutral', text: 'Equilibrio y variedad, no reglas fijas.' },
    ],
  },
];
